sudo: required
services:
  - docker

before_install:
  - docker build -t brunozrk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e "CI=true" brunozrk/react-test npm run test -- --coverage

after_success:
  - docker build -t brunozrk/multi-client ./client
  - docker build -t brunozrk/multi-nginx ./nginx
  - docker build -t brunozrk/multi-server ./server
  - docker build -t brunozrk/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push to docker hub
  - docker push brunozrk/multi-client
  - docker push brunozrk/multi-nginx
  - docker push brunozrk/multi-server
  - docker push brunozrk/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-134267255226"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
